language: android
sudo: required
jdk: openjdk11
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses:
    - '.+'
    - android-sdk-license-.+
    - google-gdk-license-.+
env:
  global:
  - END_TASK=""
before_script:
  - touch $HOME/.android/repositories.cfg
   # Android API Level 30
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;30.0.2"
   # Android API Level 31
#   - echo yes | sdkmanager "tools"
#   - echo yes | sdkmanager "platforms;android-28" # Latest platform required by SDK tools
#   - echo yes | sdkmanager "extras;android;m2repository"
#   - echo yes | sdkmanager "extras;google;m2repository"
#   - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
#   - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - chmod +x gradlew
script:
  - ./gradlew clean assemble test
