language: android
sudo: false
jdk: oraclejdk11
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
  licenses:
    - '.+'
    - android-sdk-license-.+
    - google-gdk-license-.+
env:
  global:
  - END_TASK=""

script:
  - ./gradlew clean assemble test